### ISSUE TITLE
couldn't load resource nb_menuperso

### ISSUE THREAD

**Issue by Malarne** [nlmarcio/fxserver-nb_menuperso#5]
Bonjour, j'ai fait toutes les modifs comme indiquées mais lorsque je me connecte a mon serveur (ou n'importe qui d'autre) j'ai droit a une erreure "couldn't load resource nb_menuperso.:("

**Comment by RissCrew** [comment]
Moi aussi j'ai la même erreur, bizzare :/

**Comment by elit4501** [comment]
avez réglé le problème ?

**Comment by TankHord** [comment]
je sais quoi faire quand tu ouvre le .rar clique sur nb_menuperso et puis met ce lui a l'interieur dans ton [esx]

**Comment by cptfalko** [comment]
Bonjour, j'ai le même soucis j'ai même refais 3 fois la manipulation, et comme TankHord j'ai pris le dossier a l'intérieur, mais j'ai "couldn't load resource nb_menuperso.:(" je ne comprend pas si quelqu'un a une solution
