### ISSUE TITLE
Pointer du doigt

### ISSUE THREAD

**Issue by Altaris62** [nlmarcio/fxserver-nb_menuperso#7]
FR : Salut :)
La fonction pointer du doigt chez moi ne fonctionne pas :/
Pas d'erreur dans F8...
Une idée ?
EN : Hey ! :)
The finger pointing function in my house doesn't work:/
No error in F8...
Any idea ?

**Comment by TanguyOrtegat** [comment]
press key B to point your finger

appuyes sur la touche B pour pointer du doigt
